# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=5001
@version=v10
# version from 01 to 10

GET https://{{hostname}}:{{port}}/api/{{version}}/Authors

###

GET https://{{hostname}}:{{port}}/api/{{version}}/Authors/1
